name: 'Get Docker image'
description: 'Get Docker image from ghcr.io'
inputs:
  image-tags:
    description: 'Docker image tags from build-image job'
    required: true
  github-token:
    description: 'GitHub token for logging into ghcr.io'
    required: true
outputs:
  image-ref:
    description: "The docker image reference to use"
    value: ${{ steps.image_ref.outputs.ref }}
runs:
  using: "composite"
  steps:
    - name: Get image ref
      id: image_ref
      shell: bash
      run: echo "ref=$(echo '${{ inputs.image-tags }}' | cut -d',' -f1)" >> $GITHUB_OUTPUT
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
    - name: Pull docker image
      shell: bash
      run: docker pull ${{ steps.image_ref.outputs.ref }}
