name: Docker

on:
  push:
    branches: [ "main" ]
    paths:
      - 'util/docker/dockerfile'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'util/docker/dockerfile'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate environment.yml from python-requirements.txt
        run: |
          chmod +x util/python-requirements2conda.sh
          ./util/python-requirements2conda.sh

      - name: Log in to the container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tag) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push the Docker container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./util/docker/dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
